name: CI/CD - TechMarket Orders (K3s Blue-Green + Rollback)

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    uses: DemianH9/AUY1104-SharedWorkflows/.github/workflows/build-push-dockerhub.yml@main
    with:
      image-name: techmarket-orders
      image-tag: ${{ github.sha }}
      docker-username: demianhurtubia
    secrets:
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

  deploy:
    needs: build
    uses: DemianH9/AUY1104-SharedWorkflows/.github/workflows/deploy-blue-green-k3s.yml@main
    with:
      namespace: default
      image-uri: ${{ needs.build.outputs.image-uri }}
      app-name: techmarket-orders
      container-port: "3000"
    secrets:
      KUBECONFIG_K3S: ${{ secrets.KUBECONFIG_K3S }}
