name: CI/CD Pipeline - Cliente Compartido

on:
  push:
    tags:
      - 'v*'

jobs:
  usar-pipeline-compartida:
    # Aquí llamamos a tu repositorio original y al archivo exacto
    uses: DemianH9/AUY1104-SharedWorkflows/.github/workflows/deploy-api.yml@main
    with:
      # Reemplaza 'tu-usuario-docker' por tu usuario real en Docker Hub
      image_name: "demianhurtubia/api-cliente" 
    secrets:
      # Pasamos los secretos que el workflow reutilizable requiere
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}